// <auto-generated />
using System;
using MAVN.Service.WalletManagement.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.WalletManagement.MsSqlRepositories.Migrations
{
    [DbContext(typeof(WalletManagementContext))]
    [Migration("20200701084256_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wallet_management")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.WalletManagement.MsSqlRepositories.Entities.BonusIssuedEventDataEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("operation_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("BonusType")
                        .HasColumnName("bonus_type")
                        .HasColumnType("text");

                    b.Property<Guid>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConditionId")
                        .HasColumnName("condition_id")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnName("location_id")
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .HasColumnName("partner_id")
                        .HasColumnType("text");

                    b.Property<string>("ReferralId")
                        .HasColumnName("referral_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UnitLocationCode")
                        .HasColumnName("location_code")
                        .HasColumnType("text");

                    b.HasKey("OperationId");

                    b.ToTable("bonus_event_data");
                });

            modelBuilder.Entity("MAVN.Service.WalletManagement.MsSqlRepositories.Entities.TransferEventDataEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("text");

                    b.Property<string>("ExternalOperationId")
                        .HasColumnName("external_operation_id")
                        .HasColumnType("text");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnName("operation_id")
                        .HasColumnType("text");

                    b.Property<string>("RecipientCustomerId")
                        .IsRequired()
                        .HasColumnName("recipient_customer_id")
                        .HasColumnType("text");

                    b.Property<string>("SenderCustomerId")
                        .IsRequired()
                        .HasColumnName("sender_customer_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("transfer_event_data");
                });

            modelBuilder.Entity("MAVN.Service.WalletManagement.MsSqlRepositories.Entities.WalletFlagsEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnName("is_blocked")
                        .HasColumnType("boolean");

                    b.HasKey("CustomerId");

                    b.ToTable("wallet_flags");
                });
#pragma warning restore 612, 618
        }
    }
}
